### PR TITLE
Add gnome-xorg to the DE list

### PR DESCRIPTION
**Pull request by terencode**
$DESKTOP_SESSION can report gnome as gnome-xorg

### CODE REVIEW

**Comment by bilelmoussaoui** [comment]
I would just make detect_de fallback to gnome if it's gnome-xorg instead of this change

**Comment by terencode** [comment]
Done.

**Comment by bilelmoussaoui** [comment]
Thanks!

**Comment by terencode** [comment]
you're welcome! :+1:

**Comment by terencode** [comment]
I incorrectly read your code and this addition is in fact not needed because you query both `DESKTOP_SESSION` and `XDG_CURRENT_DESKTOP`, which the latter returns just 'gnome' even on Xorg.
This thus needs a revert.

**Comment by bilelmoussaoui** [comment]
Oh, I should have remembered what I wrote a few years ago.

**Comment by terencode** [comment]
Ahah :stuck_out_tongue: What made me think it was not working is I forgot to run sudo with -E  so it couldn't read the ENV...

**Comment by terencode** [comment]
Just a reminder you probably want to revert this.

**Comment by bilelmoussaoui** [comment]
I actually don't have the time to work on this anymore since a long time now. It doesn't hurt to keep it around for now.
CC @varlesh in case you have some free time & want to revert this

**Pull request merged**
