### PR TITLE
Update database file for wire-desktop (Electron)

### PR DESCRIPTION
**Pull request by RogueScholar**
Upon seeing that Hardcode-Tray wasn't handling the icon for the wire-desktop app, I saw that the database file needed to be updated consistent with the paths and filenames used by the current installer available from their [official Debian repository](https://github.com/wireapp/wire-desktop/wiki/How-to-install-Wire-for-Desktop-on-Linux). This is my attempt to do just that.

<details>
  <summary>Output of "apt show wire-desktop"</summary>

```bash
$ apt show wire-desktop

Package: wire-desktop
Version: 3.7.2891-2891
Priority: extra
Section: default
Maintainer: Wire Swiss <wireapp@wire.com>
Installed-Size: 239 MB
Depends: libappindicator1, libasound2, libgconf-2-4, libnotify-bin, libnss3, libxss1
Homepage: https://wire.com
License: GPL-3.0
Vendor: Wire Swiss <wireapp@wire.com>
Download-Size: 53.9 MB
APT-Manual-Installed: yes
APT-Sources: https://wire-app.wire.com/linux/debian stable/main amd64 Packages
Description: The most secure collaboration platform.
```
</details>

<details>
  <summary>Output of "dpkg -L wire-desktop" (<small>sans contents of node_modules folder per Github PR char. limit)</summary>

```bash
$ dpkg -L wire-desktop

/opt
/opt/Wire
/opt/Wire/resources.pak
/opt/Wire/libVkICD_mock_icd.so
/opt/Wire/natives_blob.bin
/opt/Wire/resources
/opt/Wire/resources/app
/opt/Wire/resources/app/css
/opt/Wire/resources/app/css/about.css
/opt/Wire/resources/app/css/wrapper.css
/opt/Wire/resources/app/renderer
/opt/Wire/resources/app/renderer/src
/opt/Wire/resources/app/renderer/src/actions
/opt/Wire/resources/app/renderer/src/actions/index.js
/opt/Wire/resources/app/renderer/src/actions/__tests__
/opt/Wire/resources/app/renderer/src/actions/__tests__/actions.spec.js
/opt/Wire/resources/app/renderer/src/reducers
/opt/Wire/resources/app/renderer/src/reducers/accountReducer.js
/opt/Wire/resources/app/renderer/src/reducers/index.js
/opt/Wire/resources/app/renderer/src/reducers/__tests__
/opt/Wire/resources/app/renderer/src/reducers/__tests__/accountReducer.spec.js
/opt/Wire/resources/app/renderer/src/reducers/contextMenuReducer.js
/opt/Wire/resources/app/renderer/src/Index.css
/opt/Wire/resources/app/renderer/src/index.jsx
/opt/Wire/resources/app/renderer/src/lib
/opt/Wire/resources/app/renderer/src/lib/util.js
/opt/Wire/resources/app/renderer/src/lib/locale.js
/opt/Wire/resources/app/renderer/src/lib/accentColor.js
/opt/Wire/resources/app/renderer/src/lib/eventType.js
/opt/Wire/resources/app/renderer/src/lib/verifyObjectProperties.js
/opt/Wire/resources/app/renderer/src/lib/__tests__
/opt/Wire/resources/app/renderer/src/lib/__tests__/localStorage.spec.js
/opt/Wire/resources/app/renderer/src/lib/__tests__/verifyObjectProperties.spec.js
/opt/Wire/resources/app/renderer/src/lib/__tests__/accentColor.spec.js
/opt/Wire/resources/app/renderer/src/lib/localStorage.js
/opt/Wire/resources/app/renderer/src/lib/__mocks__
/opt/Wire/resources/app/renderer/src/lib/__mocks__/localStorage.js
/opt/Wire/resources/app/renderer/src/containers
/opt/Wire/resources/app/renderer/src/containers/WebviewsContainer.js
/opt/Wire/resources/app/renderer/src/components
/opt/Wire/resources/app/renderer/src/components/PersonalIcon.css
/opt/Wire/resources/app/renderer/src/components/Sidebar.css
/opt/Wire/resources/app/renderer/src/components/Webview.css
/opt/Wire/resources/app/renderer/src/components/IsOnline.jsx
/opt/Wire/resources/app/renderer/src/components/TeamIcon.css
/opt/Wire/resources/app/renderer/src/components/App.jsx
/opt/Wire/resources/app/renderer/src/components/Webview.jsx
/opt/Wire/resources/app/renderer/src/components/Sidebar.jsx
/opt/Wire/resources/app/renderer/src/components/Webviews.css
/opt/Wire/resources/app/renderer/src/components/IsOnline.css
/opt/Wire/resources/app/renderer/src/components/TeamIcon.jsx
/opt/Wire/resources/app/renderer/src/components/context
/opt/Wire/resources/app/renderer/src/components/context/ContextMenuItem.jsx
/opt/Wire/resources/app/renderer/src/components/context/EditAccountMenu.jsx
/opt/Wire/resources/app/renderer/src/components/context/AddAccountTrigger.jsx
/opt/Wire/resources/app/renderer/src/components/context/ContextMenu.jsx
/opt/Wire/resources/app/renderer/src/components/context/ContextMenu.css
/opt/Wire/resources/app/renderer/src/components/App.css
/opt/Wire/resources/app/renderer/src/components/Webviews.jsx
/opt/Wire/resources/app/renderer/src/components/PersonalIcon.jsx
/opt/Wire/resources/app/renderer/index.html
/opt/Wire/resources/app/renderer/dist
/opt/Wire/resources/app/renderer/dist/bundle.js
/opt/Wire/resources/app/renderer/static
/opt/Wire/resources/app/renderer/static/webview-preload.js
/opt/Wire/resources/app/img
/opt/Wire/resources/app/img/taskbar.overlay.png
/opt/Wire/resources/app/img/logo.256.png
/opt/Wire/resources/app/img/tray-icon
/opt/Wire/resources/app/img/tray-icon/tray-with-badge
/opt/Wire/resources/app/img/tray-icon/tray-with-badge/tray.badge@1.8x.png
/opt/Wire/resources/app/img/tray-icon/tray-with-badge/tray.badge@1.33x.png
/opt/Wire/resources/app/img/tray-icon/tray-with-badge/tray.badge@5x.png
/opt/Wire/resources/app/img/tray-icon/tray-with-badge/tray.badge.png
/opt/Wire/resources/app/img/tray-icon/tray-with-badge/tray.badge@1.5x.png
/opt/Wire/resources/app/img/tray-icon/tray-with-badge/tray.badge@3x.png
/opt/Wire/resources/app/img/tray-icon/tray-with-badge/tray.badge.256.png
/opt/Wire/resources/app/img/tray-icon/tray-with-badge/tray.badge@1.25x.png
/opt/Wire/resources/app/img/tray-icon/tray-with-badge/tray.badge@4x.png
/opt/Wire/resources/app/img/tray-icon/tray-with-badge/tray.badge@2x.png
/opt/Wire/resources/app/img/tray-icon/tray-with-badge/tray.badge.gnome.png
/opt/Wire/resources/app/img/tray-icon/tray-with-badge/tray.badge@1.4x.png
/opt/Wire/resources/app/img/tray-icon/tray-with-badge/tray.badge@2.5x.png
/opt/Wire/resources/app/img/tray-icon/tray
/opt/Wire/resources/app/img/tray-icon/tray/tray@2.5x.png
/opt/Wire/resources/app/img/tray-icon/tray/tray@2x.png
/opt/Wire/resources/app/img/tray-icon/tray/tray@4x.png
/opt/Wire/resources/app/img/tray-icon/tray/tray@3x.png
/opt/Wire/resources/app/img/tray-icon/tray/tray.gnome.png
/opt/Wire/resources/app/img/tray-icon/tray/tray.png
/opt/Wire/resources/app/img/tray-icon/tray/tray@1.25x.png
/opt/Wire/resources/app/img/tray-icon/tray/tray@1.33x.png
/opt/Wire/resources/app/img/tray-icon/tray/tray@1.5x.png
/opt/Wire/resources/app/img/tray-icon/tray/tray@5x.png
/opt/Wire/resources/app/img/tray-icon/tray/tray@1.8x.png
/opt/Wire/resources/app/img/tray-icon/tray/tray.256.png
/opt/Wire/resources/app/img/tray-icon/tray/tray@1.4x.png
/opt/Wire/resources/app/img/logo.ico
/opt/Wire/resources/app/img/logo
/opt/Wire/resources/app/img/logo/256x256.png
/opt/Wire/resources/app/img/logo/32x32.png
/opt/Wire/resources/app/img/logo/logo.ico
/opt/Wire/resources/app/src
/opt/Wire/resources/app/src/renderer
/opt/Wire/resources/app/src/renderer/preload.ts
/opt/Wire/resources/app/src/renderer/menu
/opt/Wire/resources/app/src/renderer/menu/context.ts
/opt/Wire/resources/app/src/renderer/menu/preload-about.ts
/opt/Wire/resources/app/src/renderer/preload-sso.ts
/opt/Wire/resources/app/src/main.ts
/opt/Wire/resources/app/src/menu
/opt/Wire/resources/app/src/menu/developer.ts
/opt/Wire/resources/app/src/menu/TrayHandler.ts
/opt/Wire/resources/app/src/menu/system.ts
/opt/Wire/resources/app/src/lib
/opt/Wire/resources/app/src/lib/webViewFocus.ts
/opt/Wire/resources/app/src/lib/SingleSignOn.ts
/opt/Wire/resources/app/src/lib/pointInRect.ts
/opt/Wire/resources/app/src/lib/CoreProtocol.ts
/opt/Wire/resources/app/src/lib/LocalAccountDeletion.ts
/opt/Wire/resources/app/src/lib/eventType.ts
/opt/Wire/resources/app/src/lib/CertificateVerifyProcManager.ts
/opt/Wire/resources/app/src/lib/AutomatedSingleSignOn.ts
/opt/Wire/resources/app/src/lib/download.ts
/opt/Wire/resources/app/src/lib/openGraph.ts
/opt/Wire/resources/app/src/settings
/opt/Wire/resources/app/src/settings/SettingsType.ts
/opt/Wire/resources/app/src/settings/SchemaUpdater.ts
/opt/Wire/resources/app/src/settings/ConfigurationPersistence.ts
/opt/Wire/resources/app/src/locale
/opt/Wire/resources/app/src/locale/locale.ts
/opt/Wire/resources/app/src/interfaces
/opt/Wire/resources/app/src/interfaces/global.ts
/opt/Wire/resources/app/src/interfaces/main.ts
/opt/Wire/resources/app/src/interfaces/index.ts
/opt/Wire/resources/app/src/interfaces/polyfills.ts
/opt/Wire/resources/app/src/interfaces/locale.ts
/opt/Wire/resources/app/src/js
/opt/Wire/resources/app/src/js/squirrel.ts
/opt/Wire/resources/app/src/js/window-manager.ts
/opt/Wire/resources/app/src/js/lifecycle.ts
/opt/Wire/resources/app/src/js/config.ts
/opt/Wire/resources/app/src/js/getLogger.ts
/opt/Wire/resources/app/src/js/util.ts
/opt/Wire/resources/app/src/js/appInit.ts
/opt/Wire/resources/app/src/js/environment.ts
/opt/Wire/resources/app/src/js/about.ts
/opt/Wire/resources/app/src/js/initRaygun.ts
/opt/Wire/resources/app/test
/opt/Wire/resources/app/test/mocha.opts
/opt/Wire/resources/app/test/fixtures
/opt/Wire/resources/app/test/fixtures/badge.html
/opt/Wire/resources/app/test/fixtures/tray.png
/opt/Wire/resources/app/test/main
/opt/Wire/resources/app/test/main/TrayHandlerTest.js
/opt/Wire/resources/app/test/main/BeforeTest.js
/opt/Wire/resources/app/test/main/AfterTest.js
/opt/Wire/resources/app/test/main/SingleSignOnTest.js
/opt/Wire/resources/app/html
/opt/Wire/resources/app/html/about.html
/opt/Wire/resources/app/locale
/opt/Wire/resources/app/locale/strings-pt.js
/opt/Wire/resources/app/locale/strings-hr.js
/opt/Wire/resources/app/locale/strings-pl.js
/opt/Wire/resources/app/locale/strings-ro.js
/opt/Wire/resources/app/locale/strings-el.js
/opt/Wire/resources/app/locale/strings-cs.js
/opt/Wire/resources/app/locale/strings-lt.js
/opt/Wire/resources/app/locale/strings-fr.js
/opt/Wire/resources/app/locale/strings-es.js
/opt/Wire/resources/app/locale/strings-sk.js
/opt/Wire/resources/app/locale/strings-tr.js
/opt/Wire/resources/app/locale/strings-it.js
/opt/Wire/resources/app/locale/strings-et.js
/opt/Wire/resources/app/locale/strings-ru.js
/opt/Wire/resources/app/locale/strings-en.js
/opt/Wire/resources/app/locale/strings-sl.js
/opt/Wire/resources/app/locale/strings-nl.js
/opt/Wire/resources/app/locale/strings-de.js
/opt/Wire/resources/app/locale/strings-da.js
/opt/Wire/resources/app/locale/strings-fi.js
/opt/Wire/resources/app/locale/strings.js
/opt/Wire/resources/app/locale/strings-hu.js
/opt/Wire/resources/app/locale/strings-uk.js
/opt/Wire/resources/app/dist
/opt/Wire/resources/app/dist/renderer
/opt/Wire/resources/app/dist/renderer/preload-sso.js
/opt/Wire/resources/app/dist/renderer/preload-sso.js.map
/opt/Wire/resources/app/dist/renderer/preload.js
/opt/Wire/resources/app/dist/renderer/menu
/opt/Wire/resources/app/dist/renderer/menu/context.js.map
/opt/Wire/resources/app/dist/renderer/menu/preload-about.js
/opt/Wire/resources/app/dist/renderer/menu/preload-about.d.ts
/opt/Wire/resources/app/dist/renderer/menu/context.js
/opt/Wire/resources/app/dist/renderer/menu/preload-about.js.map
/opt/Wire/resources/app/dist/renderer/menu/context.d.ts
/opt/Wire/resources/app/dist/renderer/preload.d.ts
/opt/Wire/resources/app/dist/renderer/preload.js.map
/opt/Wire/resources/app/dist/renderer/preload-sso.d.ts
/opt/Wire/resources/app/dist/main.d.ts
/opt/Wire/resources/app/dist/main.js
/opt/Wire/resources/app/dist/menu
/opt/Wire/resources/app/dist/menu/system.d.ts
/opt/Wire/resources/app/dist/menu/TrayHandler.d.ts
/opt/Wire/resources/app/dist/menu/TrayHandler.js.map
/opt/Wire/resources/app/dist/menu/developer.d.ts
/opt/Wire/resources/app/dist/menu/system.js.map
/opt/Wire/resources/app/dist/menu/TrayHandler.js
/opt/Wire/resources/app/dist/menu/system.js
/opt/Wire/resources/app/dist/menu/developer.js.map
/opt/Wire/resources/app/dist/menu/developer.js
/opt/Wire/resources/app/dist/lib
/opt/Wire/resources/app/dist/lib/CoreProtocol.d.ts
/opt/Wire/resources/app/dist/lib/AutomatedSingleSignOn.js.map
/opt/Wire/resources/app/dist/lib/AutomatedSingleSignOn.d.ts
/opt/Wire/resources/app/dist/lib/pointInRect.js
/opt/Wire/resources/app/dist/lib/AutomatedSingleSignOn.js
/opt/Wire/resources/app/dist/lib/webViewFocus.js.map
/opt/Wire/resources/app/dist/lib/CertificateVerifyProcManager.d.ts
/opt/Wire/resources/app/dist/lib/eventType.d.ts
/opt/Wire/resources/app/dist/lib/eventType.js
/opt/Wire/resources/app/dist/lib/LocalAccountDeletion.d.ts
/opt/Wire/resources/app/dist/lib/eventType.js.map
/opt/Wire/resources/app/dist/lib/LocalAccountDeletion.js
/opt/Wire/resources/app/dist/lib/download.d.ts
/opt/Wire/resources/app/dist/lib/openGraph.js
/opt/Wire/resources/app/dist/lib/download.js
/opt/Wire/resources/app/dist/lib/openGraph.js.map
/opt/Wire/resources/app/dist/lib/webViewFocus.d.ts
/opt/Wire/resources/app/dist/lib/openGraph.d.ts
/opt/Wire/resources/app/dist/lib/download.js.map
/opt/Wire/resources/app/dist/lib/LocalAccountDeletion.js.map
/opt/Wire/resources/app/dist/lib/SingleSignOn.d.ts
/opt/Wire/resources/app/dist/lib/CertificateVerifyProcManager.js
/opt/Wire/resources/app/dist/lib/pointInRect.js.map
/opt/Wire/resources/app/dist/lib/CoreProtocol.js
/opt/Wire/resources/app/dist/lib/SingleSignOn.js.map
/opt/Wire/resources/app/dist/lib/CertificateVerifyProcManager.js.map
/opt/Wire/resources/app/dist/lib/webViewFocus.js
/opt/Wire/resources/app/dist/lib/pointInRect.d.ts
/opt/Wire/resources/app/dist/lib/CoreProtocol.js.map
/opt/Wire/resources/app/dist/lib/SingleSignOn.js
/opt/Wire/resources/app/dist/main.js.map
/opt/Wire/resources/app/dist/settings
/opt/Wire/resources/app/dist/settings/SettingsType.js
/opt/Wire/resources/app/dist/settings/SchemaUpdater.js
/opt/Wire/resources/app/dist/settings/SettingsType.d.ts
/opt/Wire/resources/app/dist/settings/ConfigurationPersistence.js.map
/opt/Wire/resources/app/dist/settings/SchemaUpdater.d.ts
/opt/Wire/resources/app/dist/settings/ConfigurationPersistence.js
/opt/Wire/resources/app/dist/settings/SettingsType.js.map
/opt/Wire/resources/app/dist/settings/SchemaUpdater.js.map
/opt/Wire/resources/app/dist/settings/ConfigurationPersistence.d.ts
/opt/Wire/resources/app/dist/locale
/opt/Wire/resources/app/dist/locale/locale.js
/opt/Wire/resources/app/dist/locale/locale.d.ts
/opt/Wire/resources/app/dist/locale/locale.js.map
/opt/Wire/resources/app/dist/interfaces
/opt/Wire/resources/app/dist/interfaces/main.d.ts
/opt/Wire/resources/app/dist/interfaces/locale.js
/opt/Wire/resources/app/dist/interfaces/polyfills.d.ts
/opt/Wire/resources/app/dist/interfaces/index.js.map
/opt/Wire/resources/app/dist/interfaces/polyfills.js.map
/opt/Wire/resources/app/dist/interfaces/polyfills.js
/opt/Wire/resources/app/dist/interfaces/main.js
/opt/Wire/resources/app/dist/interfaces/index.js
/opt/Wire/resources/app/dist/interfaces/global.js.map
/opt/Wire/resources/app/dist/interfaces/main.js.map
/opt/Wire/resources/app/dist/interfaces/global.js
/opt/Wire/resources/app/dist/interfaces/index.d.ts
/opt/Wire/resources/app/dist/interfaces/global.d.ts
/opt/Wire/resources/app/dist/interfaces/locale.d.ts
/opt/Wire/resources/app/dist/interfaces/locale.js.map
/opt/Wire/resources/app/dist/js
/opt/Wire/resources/app/dist/js/about.js
/opt/Wire/resources/app/dist/js/util.js
/opt/Wire/resources/app/dist/js/appInit.js
/opt/Wire/resources/app/dist/js/getLogger.js
/opt/Wire/resources/app/dist/js/config.js.map
/opt/Wire/resources/app/dist/js/initRaygun.js
/opt/Wire/resources/app/dist/js/about.js.map
/opt/Wire/resources/app/dist/js/initRaygun.js.map
/opt/Wire/resources/app/dist/js/squirrel.js
/opt/Wire/resources/app/dist/js/getLogger.js.map
/opt/Wire/resources/app/dist/js/initRaygun.d.ts
/opt/Wire/resources/app/dist/js/util.js.map
/opt/Wire/resources/app/dist/js/getLogger.d.ts
/opt/Wire/resources/app/dist/js/lifecycle.js
/opt/Wire/resources/app/dist/js/environment.js.map
/opt/Wire/resources/app/dist/js/environment.js
/opt/Wire/resources/app/dist/js/window-manager.js.map
/opt/Wire/resources/app/dist/js/appInit.js.map
/opt/Wire/resources/app/dist/js/util.d.ts
/opt/Wire/resources/app/dist/js/lifecycle.js.map
/opt/Wire/resources/app/dist/js/window-manager.d.ts
/opt/Wire/resources/app/dist/js/environment.d.ts
/opt/Wire/resources/app/dist/js/config.js
/opt/Wire/resources/app/dist/js/appInit.d.ts
/opt/Wire/resources/app/dist/js/squirrel.d.ts
/opt/Wire/resources/app/dist/js/window-manager.js
/opt/Wire/resources/app/dist/js/about.d.ts
/opt/Wire/resources/app/dist/js/lifecycle.d.ts
/opt/Wire/resources/app/dist/js/config.d.ts
/opt/Wire/resources/app/dist/js/squirrel.js.map
/opt/Wire/resources/app/package.json
/opt/Wire/resources/app/node_modules
...
/opt/Wire/resources/app/.npmrc
/opt/Wire/resources/electron.asar
/opt/Wire/libGLESv2.so
/opt/Wire/locales
/opt/Wire/locales/el.pak
/opt/Wire/locales/sw.pak
/opt/Wire/locales/ta.pak
/opt/Wire/locales/ru.pak
/opt/Wire/locales/ja.pak
/opt/Wire/locales/pl.pak
/opt/Wire/locales/zh-CN.pak
/opt/Wire/locales/cs.pak
/opt/Wire/locales/bg.pak
/opt/Wire/locales/ko.pak
/opt/Wire/locales/uk.pak
/opt/Wire/locales/sk.pak
/opt/Wire/locales/bn.pak
/opt/Wire/locales/it.pak
/opt/Wire/locales/fa.pak
/opt/Wire/locales/et.pak
/opt/Wire/locales/pt-BR.pak
/opt/Wire/locales/gu.pak
/opt/Wire/locales/en-GB.pak
/opt/Wire/locales/sl.pak
/opt/Wire/locales/tr.pak
/opt/Wire/locales/he.pak
/opt/Wire/locales/sv.pak
/opt/Wire/locales/lt.pak
/opt/Wire/locales/nl.pak
/opt/Wire/locales/te.pak
/opt/Wire/locales/lv.pak
/opt/Wire/locales/fil.pak
/opt/Wire/locales/ar.pak
/opt/Wire/locales/fr.pak
/opt/Wire/locales/kn.pak
/opt/Wire/locales/ml.pak
/opt/Wire/locales/fi.pak
/opt/Wire/locales/vi.pak
/opt/Wire/locales/nb.pak
/opt/Wire/locales/en-US.pak
/opt/Wire/locales/es.pak
/opt/Wire/locales/mr.pak
/opt/Wire/locales/id.pak
/opt/Wire/locales/es-419.pak
/opt/Wire/locales/hu.pak
/opt/Wire/locales/ro.pak
/opt/Wire/locales/th.pak
/opt/Wire/locales/sr.pak
/opt/Wire/locales/am.pak
/opt/Wire/locales/ca.pak
/opt/Wire/locales/de.pak
/opt/Wire/locales/pt-PT.pak
/opt/Wire/locales/ms.pak
/opt/Wire/locales/hi.pak
/opt/Wire/locales/zh-TW.pak
/opt/Wire/locales/hr.pak
/opt/Wire/locales/da.pak
/opt/Wire/LICENSE.electron.txt
/opt/Wire/wire-desktop
/opt/Wire/snapshot_blob.bin
/opt/Wire/swiftshader
/opt/Wire/swiftshader/libGLESv2.so
/opt/Wire/swiftshader/libEGL.so
/opt/Wire/v8_context_snapshot.bin
/opt/Wire/libffmpeg.so
/opt/Wire/chrome_200_percent.pak
/opt/Wire/libEGL.so
/opt/Wire/LICENSES.chromium.html
/opt/Wire/icudtl.dat
/opt/Wire/chrome_100_percent.pak
/usr
/usr/share
/usr/share/applications
/usr/share/applications/wire-desktop.desktop
/usr/share/doc
/usr/share/doc/wire-desktop
/usr/share/doc/wire-desktop/changelog.gz
/usr/share/icons
/usr/share/icons/hicolor
/usr/share/icons/hicolor/256x256
/usr/share/icons/hicolor/256x256/apps
/usr/share/icons/hicolor/256x256/apps/wire-desktop.png
/usr/share/icons/hicolor/32x32
/usr/share/icons/hicolor/32x32/apps
/usr/share/icons/hicolor/32x32/apps/wire-desktop.png
```
</details>

After making the changes to my local `/usr/share/hardcode-tray/database/wire.electron.json` consistent with [commit 9431d59](https://github.com/bilelmoussaoui/Hardcode-Tray/commit/9431d5965aca778d650a6da9defb9aea45d276a9) I ran Hardcode-Tray again and it successfully recognized and converted its tray icons. I also rebuilt from source, using my fork with the committed changes present, and encountered no errors.

Finally, I noticed that the CircleCI badge was a broken link as parsed from the README.md file, concluded that the cause was an errant hyphen in the username portion of the Github repo URL, and corrected such. Observed result is that the badge renders as expected.

### CODE REVIEW

**Comment by bilelmoussaoui** [comment]
Thanks for the MR. we already have a license here https://github.com/bilelmoussaoui/Hardcode-Tray/tree/master/license can you remove that from your PR?

**Comment by RogueScholar** [comment]
Sure thing, LICENSE file is now gone. I added it primarily to interact with a Mediawiki extension I use to help me update Wikipedia pages for FOSS projects. What are your thoughts on symlinking the GPL file in the directory you linked to above to LICENSE in the repo's root dir? Just curious.

**Comment by bilelmoussaoui** [comment]
Yeah that would be great. As currently, github doesn't detect the right license. Maybe linking it to the README file in the license directory so the user can get an idea of why we do use a double license

**Comment by bilelmoussaoui** [comment]
Any chance we could get that link so I can merge this? Thanks for this and also for the changes you have done to the wiki!

**Comment by RogueScholar** [comment]
Sorry for the lack of progress on this PR. I actually fell down the rabbit hole of FOSS licensing for a few days, attempting to better understand what standards are in place and what the best practices might be, finally ending up trying to make some kind of sense out of the [SPDX Specification](https://spdx.org/sites/cpstandard/files/pages/files/spdxversion2.1.pdf). That's what led me to name the symlinks the way I did, as that seems to be the way they want to handle projects with any sort of conjunctive licensing.

There's still more to do in order to bring the repository into full compliance with their idea of how things should be done (like adding a one-liner tag somewhere in the project README and a little bit of formatting to alter in the license folder README), but don't feel like you need to wait for any of it before merging if that's what you want to do. I'll continue to tinker with things in my fork simply because I'd like to gain some facility with properly promulgating licenses within more complex projects, and if you're interested in where it leads then we can take another twirl out on the dancefloor. :stuck_out_tongue_winking_eye:

**Comment by bilelmoussaoui** [comment]
Perfect! Thanks for the update! Will review and merge any other PR you send later.

**Pull request merged**
