### PR TITLE
Add Motrix (AUR version)

### PR DESCRIPTION
**Pull request by KspLite**
Fixed tray icon for AUR packages of Motrix.

### CODE REVIEW

**Comment by varlesh** [comment]
thx for you PR, but why `app_path `& `icons_path`duplicated?

**Comment by KspLite** [comment]
Sorry for that. I'm not familiar with this project and didn't know the exact meaning of the .json file. Please edit the file and fix it. Thanks.

**Comment by varlesh** [comment]
@KspLite what you distro and package version use? icon path to asar?
i'm now extract **Motrix 1.4.1.deb** and asar located here:
`/opt/Motrix/resources/app.asar`
Also electron version already here:
https://github.com/bilelmoussaoui/Hardcode-Tray/blob/master/data/database/motrix.electron.json

**Comment by varlesh** [comment]
or it's motrix-git from aur? they unpack asar?
`cp -r "${srcdir}/${_pkgname}/dist" "${pkgdir}/usr/lib/${_pkgname}/app"`
https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=motrix-git

**Comment by KspLite** [comment]
Yes I'm using motrix-git, and its built from source.
I think just edit one of the `/usr/lib/motrix/` to `/usr/lib/Motrix` is enough.
Sorry again for troubling you.

**Comment by rauldipeas** [comment]
Motrix script it's outdated, i improvised with this...
```
{
    "name": "Motrix",
    "app_path": [
        "/opt/Motrix/",
        "/opt/motrix/"
    ],
    "icons_path": [
        "/opt/Motrix/resources/",
        "/opt/motrix/resources/"
    ],
    "binary": "app.asar",
    "script": "electron",
    "icons": {
        "tray": {
            "original": "dist/electron/static/mo-tray-colorful-normal.png",
            "theme": "motrix-tray"
        },
        "tray@1x": {
            "original": "dist/electron/static/mo-tray-dark-normal@1x.png",
            "theme": "motrix-tray"
        },
        "tray@2x": {
            "original": "dist/electron/static/mo-tray-dark-normal@2x.png",
            "theme": "motrix-tray"
        },                
        "tray-active": {
            "original": "dist/electron/static/mo-tray-colorful-active.png",
            "theme": "motrix-tray-active"
        },
		"tray-active@1x": {
            "original": "dist/electron/static/mo-tray-dark-active@1x.png",
            "theme": "motrix-tray-active"
        },
		"tray-active@2x": {
            "original": "dist/electron/static/mo-tray-dark-active@2x.png",
            "theme": "motrix-tray-active"
        }        
    }
}
```

**Comment by varlesh** [comment]
updated

**Pull request merged**
