### PR TITLE
Reincarnation of daily builds PPA

### PR DESCRIPTION
**Pull request by SmartFinn**
https://launchpad.net/~papirus/+archive/ubuntu/hardcode-tray

### CODE REVIEW

**Comment by bilelmoussaoui** [comment]
Nice work! Thanks a lot

**Comment by varlesh** [comment]
@bilelmoussaoui I think need remove 32-bit packages:
`sni-qt:i386` (DEB)
`lib32-sni-qt-patched-git` (ARCH)
Because this packages used for old software - Skype and TeamViewer and not support now. 
Also installing more 32-bit packages - it's clogs the system.

**Comment by bilelmoussaoui** [comment]
I think we should remove any mention of sni-qt as we don't support that anymore :/

**Comment by varlesh** [comment]
@bilelmoussaoui 
This list support sni-qt:
```
owncloud.json
synergy.json
screencloud.json
mumble.json
hp-printing.qt.json
bitcoin.json
teamviewer.json - Discontinued
tomahawk.json
flareget.json
wiznote.json
rescuetime.json
google-music-manager.json
qelectrotech.json
museeq.json
seafile.json
skype.json - Discontinued
```
Other apps need check... for example `hp-printing.qt` used qt4 now

**Comment by varlesh** [comment]
@bilelmoussaoui Audit for available apps on database (with Ubuntu 18.04 and Arhlinux AUR):
```
owncloud.json - Qt5
synergy.json - Qt5
screencloud.json - Qt4/Qt5
mumble.json - Qt4/Qt5
hp-printing.qt.json - Qt5
bitcoin.json - Qt5
teamviewer.json - Discontinued
tomahawk.json - Discontinued
flareget.json - Site not available
wiznote.json - Qt5
rescuetime.json - Qt4
google-music-manager.json - ???
qelectrotech.json - Qt5
museeq.json - Qt5
seafile.json - Qt5
skype.json - Discontinued
```

**Comment by varlesh** [comment]
now worked Qt4-apps only:
```
ScreenColud
Mumble
RescueTime
```

**Pull request merged**
