### PR TITLE
Fixes mullvad for papirus theme

### PR DESCRIPTION
**Pull request by dodslaser**
These are the icon names used for the mullvad tray icons in the papirus theme.

### CODE REVIEW

**Comment by bilelmoussaoui** [comment]
Can you ask upstream to update the icon names instead? the icon names are not explicit at all... so the icons creators cannot really figure out which icon is made for which reason :P

**Comment by varlesh** [comment]
this icon names used on upstream earlier:
https://github.com/PapirusDevelopmentTeam/papirus-icon-theme/issues/165

**Comment by dodslaser** [comment]
Hardcode-tray didn't work for me without changing the icon names. The icons
in papirus didn't work without hardcode-tray (in xfce4-panel). Hence the
PR. I could ask upstream to change names, but I feel like it makes more
sense to use the same names as the mullvad client.

**Comment by bilelmoussaoui** [comment]
Won't merge. The icons in the hardcode-tray database should have explicit icon names. Otherwise the icon designers wouldn't know which icon is made for which specific reason.

**Pull request closed without merging**
