### PR TITLE
Add NixNote2 to database

### PR DESCRIPTION
**Pull request by RogueScholar**
I found another one to add to the database, and @varlesh was already kind enough to [make a couple spiffy new icons](https://github.com/PapirusDevelopmentTeam/papirus-icon-theme/issues/1752) for it. Hopefully I got it all correct but if you spot anything that needs fixing just let me know.

### CODE REVIEW

**Comment by varlesh** [comment]
@RogueScholar It's not Qt and not use sni-qt. qt method  on gardcode-tray replace icons for Qt4-apps only.
Delete this lines:
```
"is_qt": true,
    "is_script": false,
    "force_create_folder": false,
    "exec_path_script": false,
    "backup_ignore": true,
```

**Comment by varlesh** [comment]
```
{
    "name": "NixNote2",
    "app_path": [ 
        "/usr/bin/nixnote2"
    ],
    "icons_path": [ 
        "/usr/share/nixnote2/images/"
    ],
    "icons": {
        "indicator": {
            "original": "/usr/share/nixnote2/images/trayicon.png",
            "theme": "nixnote2-tray"
        }
    }
}
```

**Comment by RogueScholar** [comment]
@varlesh thanks for catching my oversight, I'd forgotten that sni-qt was only for Qt4.

**Comment by bilelmoussaoui** [comment]
@RogueScholar Thanks for your contribution! What does the pull.yml does exactly? Is it related to a bot that will auto updates the AUR packages?

**Comment by RogueScholar** [comment]
@bilelmoussaoui Oh no, it's for [this bot](https://github.com/apps/pull) I've started using on my forked repos that does automatic PRs for me when they add new commits so I can stay current with upstream. I wasn't even thinking about the fact that you'd be stuck with it too, only the fact that I wanted to hurry and get it in my fork so it could do its thing if/when you accepted this PR. :laughing:

If you want, I can move the nixnote file over to my patch branch and submit from that instead, the pull.yml only needs to be in master.

**Comment by bilelmoussaoui** [comment]
@RogueScholar I would prefer separating the two, keeping this PR just for adding NixNote2 & the update to the readme so I can merge it today.

**Comment by RogueScholar** [comment]
Okay, can do. Can you take a look at the Changelog file I made to revive the link in the Wiki and let me know if you want that included too?

**Comment by bilelmoussaoui** [comment]
Oh that look nice! Thanks for taking care of that. That would be handy for later after the rewrite (should come this summer)

**Comment by bilelmoussaoui** [comment]
Any update on removing the git pull file? thanks!

**Pull request closed without merging**
